version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template samTemplate.yaml --s3-bucket webux-lambda-pipeline --output json > outputSamTemplate.json
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml